### ISSUE TITLE
plot_dendro with disconnected graphs

### ISSUE THREAD

**Issue by bjreisman** [dynverse/dynplot#32]
I came across the following error when trying to use plot_dendro on the output of a PAGA trajectory inference that yielded a graph with disconnected branches. 

```
> library(dyno)
> set.seed(1)
> data <- dyntoy::generate_dataset(
+   id = "specific_example/paga",
+   num_cells = 1000,
+   num_features = 101,
+   model = "tree",
+   normalise = FALSE
+ )
> 
> model_toy <- infer_trajectory(data, ti_paga(connectivity_cutoff = 0.2), verbose = TRUE, seed = 1)
Executing 'paga' on 'specific_example/paga'
With parameters: list(n_neighbors = 15L, n_comps = 50L, n_dcs = 15L, resolution = 1L,     embedding_type = "fa", connectivity_cutoff = 0.2),
inputs: counts, and
priors : start_id
Input saved to C:\Users\benja\AppData\Local\Temp\RtmpE9L4Ph\file3be85b1e5f31/ti
Running method using babelwhale
Running "C:\PROGRA~1\Docker\Docker\RESOUR~1\bin\docker.exe" run -e "TMPDIR=/tmp2" --workdir /ti/workspace -v \
  "/c/Users/benja/AppData/Local/Temp/RtmpE9L4Ph/file3be85b1e5f31/ti:/ti" -v \
  "/c/Users/benja/AppData/Local/Temp/RtmpE9L4Ph/file3be836e45656/tmp:/tmp2" "dynverse/ti_paga:v0.9.9.02" --dataset /ti/input.h5 --output \
  /ti/output.h5
Output saved to C:\Users\benja\AppData\Local\Temp\RtmpE9L4Ph\file3be85b1e5f31/ti/output.h5
Attempting to read in output with hdf5> plot_dimred(model_toy)
Coloring by milestone
Using milestone_percentages from trajectory
```
![image](https://user-images.githubusercontent.com/22528952/55970290-e3bf3000-5c44-11e9-98b9-a554297e0b2b.png)

That works great 👍 
However, the `plot_dendro` function doesn't work as well: 
```
> plot_dendro(model_toy)
root cell or milestone not provided, trying first outgoing milestone_id
Using '2' as root
Error in density.default(y, n = nbins, adjust = adjust) : 
  'x' contains missing values
```
I suppose its not well defined how to draw a dendrogram with branches that aren't all connected, but I thought I'd flag this just in case there's a way to do it. 😄

**Comment by zouter** [comment]
Hi @bjreisman 

You're right, this function should error if you try to give it anything that is not a tree. I'll add this once we rework dynplot a bit (which is coming up soon).

Thanks!

**Comment by rcannood** [comment]
I added support for this in the devel branch. You need to make sure `add_root` sets the root milestones, or this function won't work.

```r
library(dynplot)
library(tidyverse)

trajectory <- example_disconnected %>% 
  add_root(root_milestone_id = c("T1_M1", "T2_M1"))

patchwork::wrap_plots(
  plot_dendro(trajectory),
  plot_graph(trajectory)
)
```

![Screenshot from 2021-06-15 11-12-33](https://user-images.githubusercontent.com/553642/122026611-ab8a7d80-cdca-11eb-80f0-576028d4caf0.png)
