### ISSUE TITLE
How to make points smaller in plot_dimred

### ISSUE THREAD

**Issue by lambdamoses** [dynverse/dynplot#40]
I really don't like the clumped look in this kind of plot with about 10k cells: I suppose it will be worse with more cells.

![](https://res.cloudinary.com/lambdamoses/image/upload/v1557738843/000003-2.png)

Normally, in Seurat or monocle, I would use a smaller point size and lower alpha. I tried the `alpha_cells` argument, but the plot still looks really clumped. I can't find an argument in `plot_dimred` to change point size.

**Comment by rcannood** [comment]
Hey @lambdamoses ! 

Thank you for the suggestion. In the most recent version of dynplot, I added in the `alpha_cells` and `size_cells` parameters to the plotting functions. Let me know if these are working for you :)

Robrecht

**Comment by duernaT** [comment]
Hi, thank you for this wonderful package.
I have a plot_dimred question as well,
can we change the grouping color by ourselves?

**Comment by rcannood** [comment]
Closing this issue since it was solved in dynplot 1.0.2.

@duernaT, please see the new issue I created for you.

Robrecht
