### ISSUE TITLE
I have a plot_dimred question as well, can we change the grouping color by ourselves?

### ISSUE THREAD

**Issue by rcannood** [dynverse/dynplot#46]
Hi, thank you for this wonderful package.
I have a plot_dimred question as well,
can we change the grouping color by ourselves?

_Originally posted by @duernaT in https://github.com/dynverse/dynplot/issues/40#issuecomment-617512148_

**Comment by rcannood** [comment]
Hello @duernaT, 

Yes, you can, by providing meta--information on the milestones and passing this to the plot_dimred function. For example:

```r
library(dyno)
library(tibble)

data(example_trajectory)

example_trajectory$milestone_ids

milestone_info <- tribble(
  ~milestone_id, ~color,
  "milestone_begin", "red",
  "milestone_end", "green"
)

plot_dimred(
  example_trajectory, 
  color_milestones = "given", 
  milestones = milestone_info
)
```
![Screenshot from 2020-04-24 11-54-33](https://user-images.githubusercontent.com/553642/80200063-63d2f080-8622-11ea-800f-158c8ab2c6c0.png)

**Comment by duernaT** [comment]
> Hello @duernaT,
> 
> Yes, you can, by providing meta--information on the milestones and passing this to the plot_dimred function. For example:
> 
> ```r
> library(dyno)
> library(tibble)
> 
> data(example_trajectory)
> 
> example_trajectory$milestone_ids
> 
> milestone_info <- tribble(
>   ~milestone_id, ~color,
>   "milestone_begin", "red",
>   "milestone_end", "green"
> )
> 
> plot_dimred(
>   example_trajectory, 
>   color_milestones = "given", 
>   milestones = milestone_info
> )
> ```
> 
> ![Screenshot from 2020-04-24 11-54-33](https://user-images.githubusercontent.com/553642/80200063-63d2f080-8622-11ea-800f-158c8ab2c6c0.png)

Wow! Thank you so much!
It looks nice.
So I guess I can use the same idea and change the grouping (cluster) color as well. I will try.

I really appreciate your quick response.

Best,
Duerna

**Comment by wumed** [comment]
You can directly use 
_+ scale_color_manual(values = my36colors)_
to DIY the color

**Comment by rcannood** [comment]
That's a good solution too !

**Comment by erzakiev** [comment]
Hello Robrecht, 
Can we similarily recolor not the milestones, but rather grouping?
(aside from the post-hoc ggplot2 re-coloring hack)
