### ISSUE TITLE
Error encountered for infer_trajectory

### ISSUE THREAD

**Issue by jingshuw** [dynverse/dynplot#48]
I encounter this error in infer_trajectory(), even using the sample code. This error is replicated in both a mac and Linux computer, even after I have updated all depending R packages:

> dataset <- example_dataset
> method <- get_ti_methods(as_tibble = FALSE)[[1]]$fun
> 
> trajectory <- infer_trajectory(dataset, method())
Error in match.arg(backend, choices = c("docker", "singularity")) : 
  'arg' should be one of “docker”, “singularity”

**Comment by rcannood** [comment]
Sounds like you may need to recreate your [babelwhale config](https://github.com/dynverse/babelwhale#babelwhale-talk-to-docker-and-singularity-from-r). Can you verify whether this fixes your problem?

**Comment by rcannood** [comment]
Update: it seems that you don't have docker or singularity installed. I'm updating babelwhale so that it will create a helpful error message in the future.
