### ISSUE TITLE
Plot_heatmap doesn't reflect the trajectory properly for non-linear trajectories

### ISSUE THREAD

**Issue by Helena-todd** [dynverse/dynplot#50]
The structure in the heatmap resulting from dynplot::plot_heatmap seems more complex than necessary if I install all the latest dynverse packages. For instance, this code:

```
list_datasets <- dynbenchmark::list_datasets()[[1]]
dta <- dynbenchmark::load_dataset(list_datasets[31])
dynplot::plot_heatmap(dta)
```

should simply return a heatmap with three branches: E18 > P2#1 > P5#1; E18 > P2#2 > P5#2; and E18 > P2#3 > P5#3
However, the structure in the heatmap that I obtain is the following: E18 > P2#1 > P2#2 > P2#3 > P5#1 > P5#2 > P5#3

I checked on other datasets, the milestones are not always ordered by alphabetic order as is the case with this dataset, the euro must come from somewhere else.

**Comment by colapili** [comment]
Hi Helena-todd, 

Have you solve your problem ? I am interested by the solution... 

Thank you 

Nicolas

**Comment by Helena-todd** [comment]
Hi Nicolas,

Unfortunately I haven't found a solution to solve this issue yet.

Best regards,

Helena

**Comment by rcannood** [comment]
Hello @Helena-todd and @colapili,

Sorry for the long wait! This issue should now have been solved in the `devel` branch. Could you verify that it now works for you?

Robrecht

**Comment by Helena-todd** [comment]
Hi rcannood,

Yes, re-installing the devel branch of dynplot fixed the issue for me, thanks a lot! 

Helena

**Comment by rcannood** [comment]
Closing this issue as it has been solved! :)
