### ISSUE TITLE
Controlling colour scale

### ISSUE THREAD

**Issue by TJCooperIL** [dynverse/dynplot#51]
Fantastic package, thank you!

`plot_dimred(model, feature_oi = "Rsad2", expression_source = object_expression, label_milestones = FALSE)`

When plotting feature expression (e.g. with plot_dimred) is it possible to control the colour scale i.e. set the minimum and maximum values? This would be useful when visually comparing trajectories where the same genes are expressed but their levels are different (and biologically important). 

If not, would it be possible to add this to the devel branch?

**Comment by TJCooperIL** [comment]
I apologise, I forgot that dynplot returns ggplot2 objects and I can do this using scale_colour_gradientn :)

**Comment by colapili** [comment]
Hello TJCooperIL, 

I'm not very familiar with the R language so your solution interests me. Can you please explain please ?  

Thank you 

Nicolas

**Comment by rcannood** [comment]
Indeed. Also, see #46.
